# Generated by Django 5.0.6 on 2024-10-23 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargo_freeze_alter_cargo_packaging'),
        ('main', '0002_initial'),
        ('transport', '0003_transport_freeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frozen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frozen_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата - Час створення')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.cargo')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport')),
            ],
        ),
    ]
