# Generated by Django 5.1.2 on 2024-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_country_region_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='act_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/acts/'),
        ),
        migrations.AddField(
            model_name='event',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/invoices/'),
        ),
    ]
