# Generated by Django 5.1.2 on 2024-11-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_alter_cargo_payment_moment'),
        ('main', '0005_event_act_file_event_invoice_file'),
        ('transport', '0004_remove_transport_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='act_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/acts/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_cargo', to='cargo.cargo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/invoices/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_transport', to='transport.transport'),
        ),
    ]
