# Generated by Django 5.1.2 on 2024-11-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_alter_cargo_payment_moment'),
        ('main', '0006_alter_event_act_file_alter_event_cargo_and_more'),
        ('transport', '0004_remove_transport_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozen',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frozen_set', to='cargo.cargo'),
        ),
        migrations.AlterField(
            model_name='frozen',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frozen_set', to='transport.transport'),
        ),
    ]
