# Generated by Django 5.0.6 on 2024-09-22 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва вантажу')),
                ('weight_max', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вага до (кг)')),
                ('volume_max', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Об'єм до (м³)")),
                ('length', models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99.99)], verbose_name='Довжина (м)')),
                ('width', models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99.99)], verbose_name='Ширина (м)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(99.99)], verbose_name='Висота (м)')),
                ('packaging', models.CharField(choices=[('EURO 1,2x0,8 м', 'EURO 1,2x0,8 м'), ('FIN 1,2x1 м', 'FIN 1,2x1 м'), ('1x1 м', '1x1 м'), ('1,1x1,1 м', '1,1x1,1 м'), ('1,2x1,2 м', '1,2x1,2 м'), ('Нестандартная', 'Нестандартная'), ('Биг-бег', 'Биг-бег'), ('Мешок', 'Мешок'), ('Связка', 'Связка'), ('Сетка', 'Сетка'), ('Тюк', 'Тюк'), ('Блок', 'Блок'), ('Бочка', 'Бочка'), ('Чушка', 'Чушка'), ('Ящик', 'Ящик'), ('Коробка', 'Коробка'), ('Пачка', 'Пачка'), ('Упаковка', 'Упаковка'), ('Swap body', 'Swap body'), ("45'", "45'"), ("40'", "40'"), ("20'", "20'"), ('Бухта', 'Бухта'), ('Рулон', 'Рулон'), ('Барабан', 'Барабан'), ('Баллон', 'Баллон'), ('Канистра', 'Канистра'), ('Ведро', 'Ведро'), ('Навалом', 'Навалом'), ('Насыпью', 'Насыпью'), ('Без упаковки', 'Без упаковки')], max_length=100, verbose_name='Пакування')),
                ('payment_type', models.CharField(choices=[('CASH', 'нал.'), ('BANK', 'безнал.'), ('COMBO', 'комб.'), ('ELEC', 'эл. платеж'), ('CARD', 'карта')], default='default', max_length=100, verbose_name='Форма оплати')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сума коштів')),
                ('currency', models.CharField(default='грн', max_length=10, verbose_name='Валюта')),
                ('payment_moment', models.CharField(choices=[('LOAD', 'на загрузке'), ('UNLOAD', 'на выгрузке'), ('ORIGINALS', 'по оригиналам'), ('DEFERRED', 'отсрочка платежа')], max_length=100, verbose_name='Момент оплати')),
                ('photo', models.ImageField(blank=True, upload_to='cargo_photos/%Y/%m/%d/', verbose_name='Фото')),
                ('notes', models.TextField(blank=True, verbose_name='Примітка')),
                ('published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
            },
        ),
        migrations.CreateModel(
            name='LoadUnload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
