# Generated by Django 5.0.6 on 2024-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='freeze',
            field=models.BooleanField(default=False, verbose_name='Заморожування'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='packaging',
            field=models.CharField(choices=[('Без упаковки', 'Без упаковки'), ('EURO 1,2x0,8 м', 'EURO 1,2x0,8 м'), ('FIN 1,2x1 м', 'FIN 1,2x1 м'), ('1x1 м', '1x1 м'), ('1,1x1,1 м', '1,1x1,1 м'), ('1,2x1,2 м', '1,2x1,2 м'), ('Нестандартна', 'Нестандартна'), ('Біг-бег', 'Біг-бег'), ('Мішок', 'Мішок'), ('В’язка', 'В’язка'), ('Сітка', 'Сітка'), ('Тюк', 'Тюк'), ('Блок', 'Блок'), ('Бочка', 'Бочка'), ('Чушка', 'Чушка'), ('Ящик', 'Ящик'), ('Коробка', 'Коробка'), ('Пачка', 'Пачка'), ('Упаковка', 'Упаковка'), ('Swap body', 'Swap body'), ("45'", "45'"), ("40'", "40'"), ("20'", "20'"), ('Бухта', 'Бухта'), ('Рулон', 'Рулон'), ('Барабан', 'Барабан'), ('Балон', 'Балон'), ('Каністра', 'Каністра'), ('Відро', 'Відро'), ('Навалом', 'Навалом'), ('Насипом', 'Насипом')], max_length=100, verbose_name='Пакування'),
        ),
    ]
