# Generated by Django 5.0.6 on 2024-10-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargo_freeze_alter_cargo_packaging'),
        ('main', '0004_country_region_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Вантаж', 'verbose_name_plural': 'Вантажи'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_from_cargos', to='main.city', verbose_name='Місто віправлення'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_to_cargos', to='main.city', verbose_name='Місто призанчення'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='country_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_from_cargos', to='main.country', verbose_name='Країна віправлення'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='country_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_to_cargos', to='main.country', verbose_name='Країна призанчення'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='region_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_from_cargos', to='main.region', verbose_name='Регіон віправлення'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='region_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_to_cargos', to='main.region', verbose_name='Регіон призанчення'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='payment_moment',
            field=models.CharField(choices=[('LOAD', 'на загрузці'), ('UNLOAD', 'на вигрузці'), ('ORIGINALS', 'по оригіналам'), ('DEFERRED', 'відсрочка оплати')], max_length=100, verbose_name='Момент оплати'),
        ),
    ]
