# Generated by Django 5.1.2 on 2024-11-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_cargo_options_cargo_city_from_cargo_city_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='payment_moment',
            field=models.CharField(choices=[('LOAD', 'На загрузці'), ('UNLOAD', 'На вигрузці'), ('ORIGINALS', 'По оригіналам'), ('DEFERRED', 'Відсрочка оплати')], max_length=100, verbose_name='Момент оплати'),
        ),
    ]
