# Generated by Django 5.0.6 on 2024-10-30 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_complaint_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_company',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.BigIntegerField(max_length=12, null=True, validators=[django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
