# Generated by Django 5.1.2 on 2024-11-01 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_name_company_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.BigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
