# Generated by Django 5.0.6 on 2024-09-22 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoadUnload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_date', models.DateField()),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('license_plate', models.CharField(max_length=8, unique=True, verbose_name='Номерний знак')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2024)], verbose_name='Рік випуску')),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Максимальна вага (кг)')),
                ('max_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Максимальний об'єм (м³)")),
                ('photo', models.ImageField(blank=True, upload_to='transport_photos/%Y/%m/%d/', verbose_name='Фото')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('published', models.BooleanField(choices=[(False, 'Недоступний'), (True, 'Доступний')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('status', models.CharField(choices=[('Search', 'Searching'), ('IN_TRANSIT', 'In Transit'), ('Busy', 'Busy')], default='Search', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Транпорт',
                'verbose_name_plural': 'Транпорт',
            },
        ),
    ]
