# Generated by Django 5.0.6 on 2024-09-22 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transport',
            name='body_type',
            field=models.ManyToManyField(related_name='body_type', to='transport.bodytype', verbose_name='Тип кузова'),
        ),
        migrations.AddField(
            model_name='transport',
            name='load_unload',
            field=models.ManyToManyField(related_name='load_unload', to='transport.loadunload', verbose_name='Завантаження/Розвантаження'),
        ),
        migrations.AddField(
            model_name='transport',
            name='permissions',
            field=models.ManyToManyField(related_name='permissions', to='transport.permissions', verbose_name='Дозволи'),
        ),
    ]
