# Generated by Django 5.0.6 on 2024-10-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='freeze',
            field=models.BooleanField(default=False, verbose_name='Заморожування'),
        ),
    ]
