# Generated by Django 5.0.6 on 2024-10-28 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_country_region_city'),
        ('transport', '0003_transport_freeze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='to_location',
        ),
        migrations.AddField(
            model_name='transport',
            name='city_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_from_tr', to='main.city', verbose_name='Місто віправлення'),
        ),
        migrations.AddField(
            model_name='transport',
            name='city_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_to_tr', to='main.city', verbose_name='Місто призанчення'),
        ),
        migrations.AddField(
            model_name='transport',
            name='country_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_from_tr', to='main.country', verbose_name='Країна віправлення'),
        ),
        migrations.AddField(
            model_name='transport',
            name='country_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_to_tr', to='main.country', verbose_name='Країна призанчення'),
        ),
        migrations.AddField(
            model_name='transport',
            name='region_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_from_tr', to='main.region', verbose_name='Регіон віправлення'),
        ),
        migrations.AddField(
            model_name='transport',
            name='region_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_to_tr', to='main.region', verbose_name='Регіон призанчення'),
        ),
    ]
